
query_sequences.Path : /home/jpereira/OEs/OE1/toxo_reads/TGME49_Mit_ONT_reads.fasta
cont_references.Folder : /home/jpereira/OEs/OE1.v2/cont_refs
validation.sequence_blocks: /home/jpereira/OEs/Blocks_Namasivayam_without_p.fa

Results.Folder : /home/jpereira/OEs/Results/OE1/NamSeqs 

filter_sizes.rule : True
filter_sizes.min_read_length: 250

join_cont_refs.rule : True

map_contamination.rule: True
map_contamination.threads: 30

discard_contamination.rule: True
#discard_contamination.min_coverage:  90

GC_check.rule: True
GC_check.max_GC : 40

find_str.rule: True

discard_str.rule: True
discard_str.tandem_coverage: 0.50

#TODO:
# Takes the decontaminated sequences and checks wich one are covered
# by diferent target of the target recombiant sequence.
# All sequence with at leas a 50% of coverage are conserved
fragmet_coverage.rule: True

blast_to_abc.rule: True
blast_to_abc.min_aln_identity: 95
blast_to_abc.min_aln_length: 50
blast_to_abc.min_blast_word_size: 20
blast_to_abc.threads: 60

mcl_clustering.rule: True
mcl_clustering.inflation: 1.4